import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className="h-full bg-black">
      <body
        className={[
          // tus fuentes
          geistSans.variable,
          geistMono.variable,
          inter.variable,
          // layout y fondo
          "antialiased font-inter",
          "min-h-dvh w-screen overflow-x-hidden",
          "bg-black text-white",
          "flex flex-col",
        ].join(" ")}
      >
        <Header />

        {/* El main empuja el footer al fondo */}
        <main className="flex-1 w-full">
          {/* Contenido centrado con límite de ancho */}
          <div className="mx-auto w-full max-w-[1920px]">{children}</div>
        </main>

        <Footer />
      </body>
    </html>
  );
}
